#!/bin/sh

cp /usr/src/app/config.json.sample /usr/src/app/config.json

sed -i 's/<username>/'${USERNAME}'/;s/<password>/'${PASSWORD}'/;s/<debugVerified>/'${DEBUGVERIFIED}'/;s/<onlyVerified>/'${ONLYVERIFIED}'/' /usr/src/app/config.json

cd /usr/src/app
exec npm start
